### ISSUE TITLE
Error in load in QGIS version 3.24.3-Tisler

### ISSUE THREAD

**Issue by dpoursanidis** [SMByC/StackComposed-Qgis-processing#2]
Couldn't load plugin 'StackComposed' due to an error when calling its classFactory() method 

ImportError: tlz.curry 

Any idea how to fix it?

**Comment by XavierCLL** [comment]
Hi @dpoursanidis thanks for reporting the issue and I'm sorry for the long delay in responding to you, I think I fixed that error but forgot to mention it, please try with the new version. I'm going to close it temporarily because this is related to an old version but feel free to open it again. Thanks
